### PR TITLE
Add old blog posts

### PR DESCRIPTION
**Pull request by pfac**
Why:

* First stage of merging the new blog.

Note:

* These posts were adapted as required for the new blog, currently in
  preparation in #212;
* These posts files by themselves will produce no change whatsoever to
  the current website since the respective pages are not yet being
  generated.

### CODE REVIEW

**Comment by jfranciscosousa** [comment]
It's all just markdown files right?

**Comment by jfranciscosousa** [comment]
Btw @pfac I heavily recommend this plugin in order to massively reduce gatsby build times, especially for images. https://www.gatsbyjs.org/packages/gatsby-plugin-netlify-cache/

This will use the netlify cache up to 2GB I believe (if it's superior, Netlify will rebuild from scratch)

Try and merge that before the blog itself or you can run out of build minutes pretty fast.

**Comment by pfac** [comment]
> It's all just markdown files right?

Yes, it's just the markdown files of the posts in #212, so you can focus on reviewing actual code instead of 11K lines of jabbering.

**Comment by pfac** [comment]
> Btw @pfac I heavily recommend this plugin in order to massively reduce gatsby build times, especially for images. https://www.gatsbyjs.org/packages/gatsby-plugin-netlify-cache/
> 
> This will use the netlify cache up to 2GB I believe (if it's superior, Netlify will rebuild from scratch)
> 
> Try and merge that before the blog itself or you can run out of build minutes pretty fast.

uuu neat. Will take care of it right away in another PR.

**Pull request merged**
