### PR TITLE
Remove image placeholders on JS disabled

### PR DESCRIPTION
**Pull request by pfac**
Why:

* If Javascript is disabled all images loaded lazily are not shown
  because the placeholder never leaves.

### CODE REVIEW

**Comment by jfranciscosousa** [comment]
This ok, however, that hook is badly named. It should be `useIsMounted` and not `useDetectJavascript`.

But why? Because basically if we didn't have the splash screen, we would see the images **without** the placeholders. The javascript would need to be mounted for the browser to evaluate it and only after that would the image placeholders disappear.

The trick would be to render a `noscript` tag with inline styles, that just apply `display: none` to that element. I already do that somewhere, you could extract that behavior into a `HideInNoscript` component :joy:

**Comment by pfac** [comment]
The hook name conversation is one we'll have to have later over coffee, already have some ideas in that regard. :stuck_out_tongue:

I actually considered that approach, and I'm torn between the two to be honest.

On one hand, the `display: none` approach pollutes the HTML with more than the browser actually needs if it does not have Javascript. And since, if it does, it rehydrates everything and React takes over, we could simply render the "no javascript" version in the server, which is both simpler to render and smaller to transfer, and let the rehydration bring the Javascript goodies to the party once it starts.

On the other hand, that approach gives the browser both versions and lets it do the choosing. And since 99% of the cases will have Javascript, this way the first rendering will already have all the elements in place. While nothing will actually work without React rehydrating everything, at least React will have less DOM changes to do.

I keep going back and forth between two approaches, unable to completely decide. So I'll take your vote as the tie breaker.

As for the wrapping element, I'm working on a feature to stop the animations on request, so I'll wait to analyse that idea since it might not fit afterwards.

**Comment by jfranciscosousa** [comment]
Yeah, we can talk later. I prefer the latter version simply because it's the one that works better. It's perfect for noscript and perfect for with script. Even if the HTML is poluted. But we are using Gatsby anyway. The HTML will always be imcompreensible :joy:

**Comment by jfranciscosousa** [comment]
You could however set a global rule for this kinds of stuff. You just have one `display: none` on the CSS and that's it. All instances of this component would then be hidden.

**Pull request merged**
