### PR TITLE
Setup Ruby with ImageOptim for SEO image generation

### PR DESCRIPTION
**Pull request by pfac**
Why:

* The SEO image generation script uses the `image_optim` Ruby gem, but
  this project does not set it up by default.

### CODE REVIEW

**Review by naps62 — APPROVED** [review]

**Comment by frm** [comment]
Out of curiosity, why was the Ruby downgrade needed?

**Comment by pfac** [comment]
Apparently Netlify reacts to the fact it has Gemfile in the repository by attempting to install these dependencies, and it is using Ruby 2.6.2 by default.

**Comment by frm** [comment]
Wait, so we downgrade the Ruby version instead of updating the version used by Netlify? It's a single file: https://docs.netlify.com/configure-builds/manage-dependencies/#ruby

**Comment by pfac** [comment]
> Wait, so we downgrade the Ruby version instead of updating the version used by Netlify? It's a single file: https://docs.netlify.com/configure-builds/manage-dependencies/#ruby

What's the problem? There's nothing Ruby related even being used in Netlify, this is just so we can version `image_optim` so the Ruby version just has to be a supported one, and we don't use `.ruby-version` with asdf-vm so this would have to be done via environment variable (which we don't need for the previous reasons). There's absolutely no impact caused by this downgrade aside using a different number.

**Pull request merged**
